### ISSUE TITLE
UnicodeDecodeError error while running doc samples  

### ISSUE THREAD

**Issue by victor-h-b** [johnbywater/eventsourcing#214]
Environment details:
- MacOS Mojave 
- Python 3.8.2

libs:
```
eventsourcing             8.2.3
SQLAlchemy                1.3.18
SQLAlchemy-Utils          0.36.6
mysql-connector-python    8.0.20
mysqlclient               1.4.6
```
-----------------

while running the exact samples from the docs, except changing the DB connection line to:
`os.environ['DB_URI'] = "mysql+mysqlconnector://root:<mypass>@localhost/mytest"`

it fails on the line:
```
    # Aggregate now exists in repository.
    assert world.id in app.repository
```

with the error:

```
Error closing cursor
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    self.dialect.do_execute(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mysql/connector/cursor_cext.py", line 272, in execute
    self._handle_result(result)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mysql/connector/cursor_cext.py", line 163, in _handle_result
    self._handle_resultset()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mysql/connector/cursor_cext.py", line 654, in _handle_resultset
    self._rows = self._cnx.get_rows()[0]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 318, in get_rows
    else self._cmysql.fetch_row()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 0: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1369, in _safe_close_cursor
    cursor.close()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mysql/connector/cursor_cext.py", line 402, in close
    self._cnx.handle_unread_result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 712, in handle_unread_result
    raise errors.InternalError("Unread result found")
mysql.connector.errors.InternalError: Unread result found
Traceback (most recent call last):
  File "/<path-to-my-file>/eventsourcing_test.py", line 60, in <module>
    assert world.id in app.repository
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/eventsourcing/infrastructure/eventsourcedrepository.py", line 79, in __contains__
    return self.get_entity(entity_id) is not None
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/eventsourcing/infrastructure/eventsourcedrepository.py", line 144, in get_entity
    return self.get_and_project_events(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/eventsourcing/infrastructure/eventsourcedrepository.py", line 200, in get_and_project_events
    return self.project_events(initial_state, domain_events)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/eventsourcing/infrastructure/eventsourcedrepository.py", line 217, in project_events
    return reduce(self._mutator_func, domain_events, initial_state)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/eventsourcing/infrastructure/base.py", line 203, in get_items
    records = self.get_records(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/eventsourcing/infrastructure/sqlalchemy/manager.py", line 205, in get_records
    results = list(query.all())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3341, in all
    return list(self)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3503, in __iter__
    return self._execute_and_instances(context)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3528, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1014, in execute
    return meth(self, multiparams, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1127, in _execute_clauseelement
    ret = self._execute_context(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    self._handle_dbapi_exception(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1515, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    self.dialect.do_execute(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mysql/connector/cursor_cext.py", line 272, in execute
    self._handle_result(result)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mysql/connector/cursor_cext.py", line 163, in _handle_result
    self._handle_resultset()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mysql/connector/cursor_cext.py", line 654, in _handle_resultset
    self._rows = self._cnx.get_rows()[0]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 318, in get_rows
    else self._cmysql.fetch_row()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 0: invalid continuation byte
```

**Comment by johnbywater** [comment]
I think there's a problem with that driver. Try a different one, perhaps one of the drivers recommended in the docs, such as `pymysql-connector-python-rf` and `PyMySQL`?
https://eventsourcing.readthedocs.io/en/stable/topics/infrastructure.html#mysql

Please let me know if you get it to work?

**Comment by victor-h-b** [comment]
@johnbywater 
thanks for the helpful link.

eventually, I ended up with the following libs:
```
eventsourcing             8.2.3
PyMySQL                   0.9.3
SQLAlchemy                1.3.18
SQLAlchemy-Utils          0.36.6
```

(I've uninstalled the `mysql-connector-python` & `mysqlclient` libs)
