### ISSUE TITLE
Premature processes disposal in MultiThreadedRunner

### ISSUE THREAD

**Issue by vladimirnani** [johnbywater/eventsourcing#223]
**Setup:**
1. System runs in a `MultiThreadedRunner`
2. One of the downstream apps has a snapshotting enabled 

**Problem:**
Following error occurs after system ran
```
   Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/eventsourcing/eventsourcing/system/runner.py", line 364, in run
    self.loop_on_prompts()
  File "/eventsourcing/eventsourcing/system/runner.py", line 394, in loop_on_prompts
    self.run_process(prompt)
  File "/eventsourcing/eventsourcing/system/runner.py", line 415, in run_process
    self._run_process(prompt)
  File "/eventsourcing/eventsourcing/domain/model/decorators.py", line 201, in wrapper
    return func(*args, **kwargs)
  File "/eventsourcing/eventsourcing/domain/model/decorators.py", line 201, in wrapper
    return func(*args, **kwargs)
  File "/eventsourcing/eventsourcing/system/runner.py", line 424, in _run_process
    self.app.run(prompt)
  File "/eventsourcing/eventsourcing/application/process.py", line 268, in run
    self.take_snapshots(new_events)
  File "/eventsourcing/eventsourcing/application/process.py", line 651, in take_snapshots
    assert self.snapshotting_policy
AssertionError
```

**Cause**
`thread.join()` is invoked after `process.close()`
and at that point `snapshotting_policy` is already disposed

**Solution**
Close processes after their threads are joined

**Comment by johnbywater** [comment]
Thanks for doing all of this so nicely @vladimirnani.
